### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Cereal38** [Cereal38/interim#1]
- [x] Création de table
- [x] CHECKs
- [x] Récupérer les informations des tables (noms / colonnes)
- [x] Afficher table
- [x] Afficher colonne
- [x] Fonctionnalités préfaites utiles pour boite d'intérim
- [x] INSERT ligne
- [x] DELETE ligne
- [x] UPDATE ligne
- [x] Commande libre
- [x] Pas de reset automatique
- [x] Reset manuel
- [x] Contraintes de domaines PDF
- [x] Test NON OK
- [x] Tests OK
- [x] Regex dans l'application
- [x] Supprimer les fichiers inutiles du repo
- [x] Correction du modèle UML
- [x] README
- [x] Requêtes paramétrables
